---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes
      when: ansible_os_family == 'Debian'

    - debug:
        var: ansible_os_family

  roles:
    - role: kitos9112.rpimonitor
